spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug

jwt:
  secret: ${JWT_SECRET}
  expire_time:
    access_token: ${ACCESS_TOKEN_EXPIRE_TIME}
    refresh_token: ${REFRESH_TOKEN_EXPIRE_TIME}

frontend:
  url: ${FRONTEND_URL}